### ISSUE TITLE
Can't locate Bio/DB/SeqFeature/Store.pm in @INC (you may need to install the Bio::DB::SeqFeature::Store module)

### ISSUE THREAD

**Issue by a2htray** [GMOD/cmap#1]
i had install the `Bio::DB::SeqFeature::Store` module by using command `perl -MCPAN -e "force install Bio::DB::SeqFeature::Store"`, i need to import the gff data to the data source. thanks a lot

`Can't locate Bio/DB/SeqFeature/Store.pm in @INC (you may need to install the Bio::DB::SeqFeature::Store module) (@INC contains: /etc/perl /usr/local/lib/x86_64-linux-gnu/perl/5.20.2 /usr/local/share/perl/5.20.2 /usr/lib/x86_64-linux-gnu/perl5/5.20 /usr/share/perl5 /usr/lib/x86_64-linux-gnu/perl/5.20 /usr/share/perl/5.20 /usr/local/lib/site_perl .) at /usr/local/share/perl/5.20.2/Bio/GMOD/CMap/Admin/Interactive.pm line 3753.
`

**Comment by nathanweeks** [comment]
Hi,
That module is part of BioPerl. You should be able to use your OS's package manager to install it, or follow the directions here: http://bioperl.org/INSTALL.html

**Comment by nathanweeks** [comment]
I'll close this one for now. If you're still having problems, feel free to reopen it.
